### ISSUE TITLE
libSampleRate missing config.h

### ISSUE THREAD

**Issue by erikieNL** [mjrgh/DCSExplorer#1]
Hi, trying to compile your code. However one file is missing on github in libsamplerate project: config.h
Can you add that? Thanks a lot

**Comment by mjrgh** [comment]
Done. (Looks like libsamplerate's .gitignore excludes it explicitly, probably because they intend for it to be derived via the linux configure script, but for the purposes of the VS project I wanted it all preconfigured for one-step building.)

**Comment by erikieNL** [comment]
Thanks compile done. Will now have a look at your code ;)
