### ISSUE TITLE
Modifying DCS roms from Hangtime video game (and maybe others?) not working properly.

### ISSUE THREAD

**Issue by Asure** [mjrgh/DCSExplorer#2]
I'm working on expanding the DCS sound roms for NBA Hangtime.
I had already started hex editing and adding a ton of samples and some music before i found your excellent tool.
I decided to re-do my work using your tools instead of leaked tools in DOSBOX.

- I restarted with a clean unmodded NBA Hangtime romset.
- In DCSExplorer i can play, extract and work with the DCS roms just fine.
- However, DCSEncoder does not want to add my extended 'create a player' tune stating it needs more than the 8 1MB chips.

My script is basically this:

Track $07bf Channel 0 {    
    SetMixingLevel(level 120);
Loop {
    Play("create.wav" (bitrate=96000)); 
}

Output: 

-- snip --

D:\dcs>DCSEncoder.exe -o new --patch nba.zip superhangtime.scr                                                          
Loading prototype ROM set from nba.zip                                                                                  
Compiling script from superhangtime.scr                                                                                 
Encoding create.wav : OK, 6188 DCS frames, 325244 bytes in ROM (9.1:1 compression, 54750 avg bps)       
                                                                                                                                        
Generating new ROM set to new                                                                                           
ROM creation failed: Out of space in the ROM layout.  The DCS pinball sound boards are limited to 8 ROM chips, but this build requires at least 9 chips at the current size setting of 1024K bytes per chip.

**Comment by Asure** [comment]
I did some additional test with a pinball rom: NBA fastbreak, adding the same sample.
It added U7 and U8, 2Mbytes, for adding a 325244 byte sample. This seems strange to me. 
(From hexediting i would have expected it to add a single 1Mbyte rom and put the new 325244 bytes there.)

--- output ---
Loading prototype ROM set from nbaf_31.zip
Compiling script from test.scr
Encoding create.wav : OK, 6188 DCS frames, 325244 bytes in ROM (9.1:1 compression, 54750 avg bps)

Generating new ROM set to test.zip
ROM .zip file layout:
Chip  Size   Bytes Used  Unused  Filename
U2    1M     1048566     10      fb-s2.3_0
U3    1M     1048572     4       fb-s3.1_0
U4    1M     1048544     32      fb-s4.1_0
U5    1M     1048532     44      fb-s5.1_0
U6    1M     1048556     20      fb-s6.1_0
U7    1M     1048572     4       fb-s7.1_0
U8    1M     700888      347688  fb-s8.1_0

ROM creation succeeded
--- end output ---

I also tried replacing track #5 with a the new sample, but this errors out. 
I had assumed from the readme.md that "Track definitions in the script that assign track numbers already defined in the ROM replace the corresponding ROM tracks."

--- output ---
Loading prototype ROM set from nbaf_31.zip
Compiling script from test.scr
Encoding create.wav : OK, 6188 DCS frames, 325244 bytes in ROM (9.1:1 compression, 54750 avg bps)
test.scr(18): error: Track #5 has already been defined in this script; the original definition will be discarded

Script compilation failed with 1 error, 0 warnings
No ROM images generated
--- end output ---

**Comment by mjrgh** [comment]
If you could attach the source files, I'll give them a try in the debugger and see if I can track down what's going wrong.

**Comment by Asure** [comment]
[nbaf_31.zip](https://github.com/mjrgh/DCSExplorer/files/14234464/nbaf_31.zip)
[create_wav.zip](https://github.com/mjrgh/DCSExplorer/files/14234468/create_wav.zip)
[script.zip](https://github.com/mjrgh/DCSExplorer/files/14234469/script.zip)
[hangtime.zip](https://github.com/mjrgh/DCSExplorer/files/14234470/hangtime.zip)

Attached script, wav and nba hangtime dcs roms.

**Comment by Asure** [comment]
I was able to bypass the error by changing it to EWarning in DCSCompiler.cpp lines 745+ and adding the two actions from above IF clause:

```
tokenizer.Error(EWarning, "Track #%d has already been defined in this script; the original definition will be discarded", trackNum);
track->fromRom = false;
track->steps.clear();
```

Using a known rom as base and replacing track 0005 it now generates a new rom set. With my 'unknown' NBA.ZIP set it still fails, erroring that it needs too much roms.

The generated set is still too large compared to its parent nbaf_31.zip. It created a U7 and U8 whilst it was only adding 325244 bytes.

Comparing content using DCSExplorer -s output shows what appear to be duplicated streams, i'm not sure of the cause yet.

Edit: Just using a script with a simple VAR statement like below, not adding any streams or tracks, will cause a new rom from parent nbaf_31.zip to grow with 2Mbytes, adding S7 and S8 roms. (this test was run with original code, not using the modification to the fromRom i posted above.)

```
// Two slashes start a comment
Signature "TEST ROM";
Var Y : 2;   // sets variable ID, for use with --patch
```

**Comment by Asure** [comment]
I learned some CPP and noted streamsByProtoAddr never got updated with streamAddr. Pull sent.
